
package:
  name: dryaml
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'UNKNOWN').lstrip('v') }}{% if environ.get('GIT_DESCRIBE_NUMBER', 0)|int != 0 %}.post{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}{% endif %}

source:
  path: ../


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check"


requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - dryaml

about:
  home: https://github.com/kaifronsdal/dryaml
  license: Open Source
