name: Documentation
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -el {0}
env:
  CONDA_API_KEY: ${{ secrets.QUETZ_API_KEY }}

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup conda
        uses: mamba-org/setup-micromamba@db1df3ba9e07ea86f759e98b575c002747e9e757
        with:
          condarc-file: .github/workflows/.condarc
          environment-file: environment.yml
      - name: Install package
        run: python -m pip install --no-build-isolation --no-deps --disable-pip-version-check -e .
      - name: Build docs
        run: cd docs && make html
      - name: Upload html
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_build/html

  upload:
    name: Upload Docs
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download html
        uses: actions/download-artifact@v3
        with:
          name: docs
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/610600912298/locations/global/workloadIdentityPools/doqker-devel-github-actions-pool/providers/github-actions-provider
          service_account: sa-github-actions@doqker-devel.iam.gserviceaccount.com
          token_format: access_token
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
      - name: Set ref (release)
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "docs-path=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Set ref (main)
        if: github.ref == 'refs/heads/main'
        run: echo "docs-path=latest" >> $GITHUB_ENV
      - name: Set ref (pull_request)
        if: startsWith(github.ref, 'refs/heads/') && github.ref != 'refs/heads/main'
        run: echo "docs-path=${{ github.ref }}" >> $GITHUB_ENV
      - name: Upload to Google Cloud Storage
        run: gcloud storage cp -r * gs://qc-github-artifacts/${{ github.repository }}/${{ env.docs-path }}/
