name: Windows CI
on: [push]

# Automatically stop old builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

env:
  CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
  CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
  CONDA_API_KEY: ${{ secrets.QUETZ_API_KEY }}

jobs:
  windows:
    name: "Windows – unit tests - Python ${{ matrix.PYTHON_VERSION }}"
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        with:
          condarc-file: .github/workflows/.condarc
          environment-file: environment.yml
          cache-environment: true
          create-args: >-
            python=${{ matrix.PYTHON_VERSION }}
            pytest-md
            pytest-emoji
      - name: Install repository
        run: python -m pip install --no-build-isolation --no-deps --disable-pip-version-check -e .
      - name: Checkout Quantco/pytest-action
        uses: actions/checkout@v3.3.0
        with:
          repository: Quantco/pytest-action
          ref: v2
          token: ${{ secrets.FQ_GH_TOKEN }}
          path: .github/pytest-action
      - name: Run unittests
        uses: ./.github/pytest-action
        with:
          report-title: "Unit tests Windows - Python ${{ matrix.PYTHON_VERSION }}"
          custom-arguments: --cov-report=xml ./tests
